"""Loads the .pdf knowledge base into section/page-tagged text blocks.

The document is generated by data/generate_kb_pdf.py with one explicit page
break per section (title page = page 1, section N = page N+1), and each
section heading is a numbered, all-caps line (e.g. "5. ADMISSIONS"). Page
numbers come directly from the PDF's own pagination via pypdf -- no rendering
or heuristics required, since we control both the writer and the reader.
"""

import re
from dataclasses import dataclass

from pypdf import PdfReader

HEADING_RE = re.compile(r"^\d{1,2}\.\s+[A-Z0-9][A-Z0-9 &,()/\-]*$")


@dataclass
class SectionBlock:
    section: str
    page: int
    text: str


def load_pdf_sections(path) -> list[SectionBlock]:
    reader = PdfReader(str(path))

    sections: list[SectionBlock] = []
    current_heading = None
    current_heading_page = None
    current_lines: list[str] = []

    def flush():
        if current_heading is not None:
            sections.append(SectionBlock(
                section=current_heading,
                page=current_heading_page,
                text="\n".join(current_lines).strip(),
            ))

    for page_index, page in enumerate(reader.pages, start=1):
        for line in page.extract_text().splitlines():
            line = line.strip()
            if not line:
                continue
            if HEADING_RE.match(line):
                flush()
                current_heading = line
                current_heading_page = page_index
                current_lines = []
            elif current_heading is None:
                continue  # title / subtitle before section 1
            else:
                current_lines.append(line)

    flush()
    return sections


if __name__ == "__main__":
    import sys
    from config import KB_PDF_PATH

    path = sys.argv[1] if len(sys.argv) > 1 else KB_PDF_PATH
    blocks = load_pdf_sections(path)
    for b in blocks:
        print(f"[page {b.page}] {b.section} ({len(b.text)} chars)")
